"""add check tables

Revision ID: 1b5bdb043383
Revises: 5b0e5c04dfca
Create Date: 2019-07-31 06:30:06.217833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5bdb043383'
down_revision = '5b0e5c04dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('monitor_id', sa.BigInteger(), nullable=False),
    sa.Column('check_time', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monitor', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('monitor', sa.Column('expire_time', sa.DateTime(), nullable=True))
    op.alter_column('monitor', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('monitor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('monitor', 'endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('monitor', 'expire_time')
    op.drop_column('monitor', 'create_time')
    op.drop_table('check_status')
    # ### end Alembic commands ###
