"""add index

Revision ID: 38a093f374d7
Revises: 1b5bdb043383
Create Date: 2019-08-04 18:07:56.329637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a093f374d7'
down_revision = '1b5bdb043383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_check_status_check_time'), 'check_status', ['check_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_status_check_time'), table_name='check_status')
    # ### end Alembic commands ###
