"""add indexes to check table

Revision ID: 8197c81cc034
Revises: fe9c91c57a71
Create Date: 2019-08-06 00:04:55.708523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8197c81cc034'
down_revision = 'fe9c91c57a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_check_status_monitor_id'),
                    'check_status', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_check_status_status_code'),
                    'check_status', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_status_status_code'),
                  table_name='check_status')
    op.drop_index(op.f('ix_check_status_monitor_id'),
                  table_name='check_status')
    # ### end Alembic commands ###
