"""add latency to check

Revision ID: 881c21a9237d
Revises: 8197c81cc034
Create Date: 2019-08-07 04:00:03.433110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881c21a9237d'
down_revision = '8197c81cc034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_status', sa.Column('latency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_status', 'latency')
    # ### end Alembic commands ###
