version: '3.3'
services:
  backend: 
    build: 
      context: api
      args: 
        env: dev
    command: /app/start-reload.sh
    volumes:
      - ./api:/app
    env_file:
      - env-postgres.env
    ports:
      - '8000:8000'
    networks:
      default:
        aliases:
        - 'apidash.dev'
    depends_on: 
      - db
  monitor:
    build:
      context: monitor
    env_file:
      - env-postgres.env
    depends_on: 
      - db
  db:
    image: postgres:11
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
