version: '3.3'
services:
  backend: 
    build: 
      context: .
      args: 
        env: dev
    networks: 
      default: 
        aliases: 
          - apidash
    command: /app/start-reload.sh
    volumes:
      - .:/app
    env_file:
      - env-postgres.env
    ports:
      - '8000:8000'
    depends_on: 
      - db
  db:
    image: postgres:11
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
